version: '3.8'

services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - LT_DEBUG
      - LT_LOAD_ONLY=ru,en # load only these languages, when will deploy to server, remove this line
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    volumes:
      - libretranslate_data:/libretranslate/.local/share
      - libretranslate_data:/libretranslate/.local/cache

volumes:
  libretranslate_data: